
quarkus.http.port=8081

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clientesdb
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger

quarkus.rest-client.apicpf-api.url=https://apicpf.com/
quarkus.rest-client.apicpf-api.connect-timeout=5000
quarkus.rest-client.apicpf-api.read-timeout=5000

apicpf.api.key=${APICPF_API_KEY:610fa3d201408fa249754d4200df8608b87d79c93e3105c0cac98fcbf011ec15}