

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/clientesdb
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger

quarkus.smallrye-openapi.security-scheme=oidc
quarkus.smallrye-openapi.security-scheme-name=Keycloak
quarkus.smallrye-openapi.oidc-open-id-connect-url=http://localhost:8082/realms/banco-realm/.well-known/openid-configuration
quarkus.swagger-ui.oauth-client-id=sistema-bancario-client
quarkus.swagger-ui.oauth-use-pkce-with-authorization-code-grant=true
# URL do Keycloak (ajuste para seu ambiente)
quarkus.oidc.auth-server-url=http://localhost:8082/realms/banco-realm
quarkus.oidc.client-id=sistema-bancario-client
quarkus.oidc.application-type=service
quarkus.oidc.credentials.secret=LUJvUHcVi8180GwuIDW6bRxk4npYumX1
# Habilita JWT como token de acesso
quarkus.oidc.token.issuer=http://localhost:8082/realms/banco-realm
quarkus.oidc.token.audience=account
# Mapeia roles do Keycloak para o app (ex.: roles como "cliente" ou "admin")
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.roles.role-claim-path=realm_access/roles

quarkus.rest-client.apicpf-api.url=https://apicpf.com/
quarkus.rest-client.apicpf-api.connect-timeout=5000
quarkus.rest-client.apicpf-api.read-timeout=5000
apicpf.api.key=${APICPF_API_KEY:610fa3d201408fa249754d4200df8608b87d79c93e3105c0cac98fcbf011ec15}

quarkus.cache.type=redis
quarkus.redis.hosts=redis://localhost:6379
quarkus.cache.redis.clientePFPorId.key-type=java.lang.Long
quarkus.cache.redis.clientePFPorId.value-type=sousa.banco.dto.ClientePFDTO
quarkus.cache.redis.clientePFPorId.expire-after-write=10m

quarkus.cache.redis.clientePFPorCpf.key-type=java.lang.String
quarkus.cache.redis.clientePFPorCpf.value-type=sousa.banco.dto.ClientePFDTO
quarkus.cache.redis.clientePFPorCpf.expire-after-write=10m

quarkus.cache.redis.clientesPFTodos.value-type=java.util.List
quarkus.cache.redis.clientesPFTodos.expire-after-write=5m



